### PR TITLE
Changed csproj to use patterns of image files

### PR DESCRIPTION
**Pull request by karalabecode**
I just added one .png to the Images folder inside the project dir and wondered why it didn't copy it to the bin dir.

### CODE REVIEW

**Comment by josdemmers** [comment]
Thanks that makes it more maintainable.
Where did you want to add an image?
Going to remove everything in `.\D4Companion\Images\2560x1440_SMF_en` in the next update.

All presets will then be located in `./Diablo4Companion/tree/master/downloads/systempresets` to make contributions easier.

**Comment by karalabecode** [comment]
> Thanks that makes it more maintainable. Where did you want to add an image? Going to remove everything in `.\D4Companion\Images\2560x1440_SMF_en` in the next update.
> 
> All presets will then be located in `./Diablo4Companion/tree/master/downloads/systempresets` to make contributions easier.

Sounds good! I was gonna ask how I could contribute my screenshots. That will make this PR obsolete, right?

**Comment by josdemmers** [comment]
The only images left in the project will be the `EmbeddedResources` for the GUI. Could use the pattern for that as well, but not sure that is needed because those images don't really change.

**Comment by karalabecode** [comment]
You can also just close it, as you'll have to touch this file anyway.

Btw did you consider OCR for iding the properties?

**Comment by josdemmers** [comment]
Started with template matching first so I could support all 12 languages of Diablo. Planning to use OCR later (or at least do some tests). But looking at other projects I'm not sure it will be fast enough to give real-time info for the overlay.
If it works however it would allow a lot more features.

Are you also on the Discord? Makes it easier to discuss contributing images.

> You can also just close it, as you'll have to touch this file anyway.
Will do.

**Comment by josdemmers** [comment]
Updated the project files. All preset images are now located here:
 `https://github.com/josdemmers/Diablo4Companion/tree/master/downloads/systempresets`

To add missing affixes you can add them to the image folder matching your preset:
`https://github.com/josdemmers/Diablo4Companion/tree/master/downloads/systempresets/images`

The download manager in the app uses the zip files. So you need to update the zip file matching your preset as well.

**Pull request closed without merging**
