### PR TITLE
Add 1600p_SMF_en support

### PR DESCRIPTION
**Pull request by amorimdiogo**
Added 1600p Medium font support for SDR.

### CODE REVIEW

**Comment by amorimdiogo** [comment]
@josdemmers, great work with the tool, found it recently and it was very fun to check how you made it work! Also, the Debug mode is awesome!

The reason this PR is a draft is that I could not manage to test it locally, as the app only allows to "download" presets already in master. I changed UpdateSystemPresetInfo() to use my local file instead of the uri, and it worked finally found my preset, but I still have to download it and the button is greyed out 😅
image

Maybe this could be a future update for debug mode.

Thanks you!

**Comment by josdemmers** [comment]
Thank you for the extra system preset. Good to hear you like the project!

Regarding the download button, that is disabled while the overlay is active. If you disable it you can download and change the system preset.

For local testing you don't have to use the Download button. You can directly use the selection on the left.
Add your preset to the `.\Diablo4Companion\Images\` folder and restart the app and you will be able to select it.

**Comment by amorimdiogo** [comment]
Updated the icons as suggested.

While testing locally, the items were never detected by the debugger. I had it working on my 1440 monitor though with the 1440p_SMF_en preset, so it could be the icons I captured are now too cropped, or am I missing something?

**Comment by amorimdiogo** [comment]
Maybe the issue could be the height, as this is a taller aspect ratio (16:10), and the shift key is not visible on the item.

image

**Comment by josdemmers** [comment]
Your icons are looking fine now. Must be something else. 
Let's first try to get it working at your end before merging it.

You mentioned a 1440p monitor. That pc has multiple monitors connected?

**Comment by amorimdiogo** [comment]
Your intuition was on point.

After testing individually with each monitor (laptop 1600p and widescreen 1440p), the app worked correctly. I was using it without restarting the app when changing monitors, which caused the issue.

Noticed one thing, both on 1600p_SMF_en and 1440p_SMF_en presets, the unique icon was not detected.

1440p

**Comment by amorimdiogo** [comment]
Also confirm that controller mode worked in both presets.

**Comment by josdemmers** [comment]
Great, going to merge this tomorrow.

**Comment by josdemmers** [comment]
> Noticed one thing, both on 1600p_SMF_en and 1440p_SMF_en presets, the unique icon was not detected.

Probably working fine. Unique aspects are not marked because you can't extract them.
You can verify if it works at the debug tab.

image

**Comment by josdemmers** [comment]
Merge is done, one last question. What is the ingame brightness you are using?

Is that the same as the default?
332195335-032e9499-7909-415e-ba32-362dbf053196

Reason is I was testing and updating some of the other presets and noticed that with the default ingame brightness setting changing this app setting worked better:

- Brightness Thresshold: 60 --> 70

**Pull request merged**
