### PR TITLE
added images & mappings to 1080_en

### PR DESCRIPTION
**Pull request by nebelorz**
Added ranks to barbarian's passive wallop
Added ranks to barbarian's all brawling skills
Added several mappings to the barbarian affixes
Added earthquake aspect image
Added ranks to ground stomp image

### CODE REVIEW

**Comment by josdemmers** [comment]
Hi @nebelorz thanks for the pull request.
Something went wrong with the file names though.
All "'" are replaced with an "n".

image

**Comment by nebelorz** [comment]
😐 let me check it if there's something wrong on my local zip file

**Comment by nebelorz** [comment]
everything seems fine here (I've deleted and cloned the repo just in case) 🫠:

![image](https://github.com/josdemmers/Diablo4Companion/assets/65920053/d68d8cca-d056-47e3-a34c-f69b1b3614da

**Comment by josdemmers** [comment]
Still no luck here. All ` are replaces by n. And it's only your zip file. The zip file for the other presets are looking fine.

Could you modify the files at this location instead? Then I'll create the new zip file afterwards.
https://github.com/josdemmers/Diablo4Companion/tree/master/downloads/systempresets-v2/images/1080p_SMF_en

**Pull request closed without merging**
