### PR TITLE
Merge branch 'master' of https://github.com/Ash-Cozey/Diablo4Companion

### PR DESCRIPTION
**Pull request by Ash-Cozey**
I use a 3440x1440 standard def monitor with a medium font scaling. The 2560x1440 version worked perfectly after changing the name. 

I created a relative symlink to the 2560x1440_SMF_en preset folder, and added the config to systempresets.json and a zip of the symlinked folder.

### CODE REVIEW

**Comment by josdemmers** [comment]
If only the height matters maybe it's a better idea if I rename the presets to only contain the height instead?
For example: 
- 2560x1440_SMF_en
- 3440x1440_SMF_en
Becomes:
- 1440p_SMF_en

So that there is only one 1440p_SMF_en?
What do you think?

**Comment by Ash-Cozey** [comment]
That sounds way easier to maintain, definitely a better way of doing things. I can try a few different resolutions and font scales and check to see if I notice any weird scaling this afternoon to confirm this should work for other resolutions as well if you want.

**Comment by josdemmers** [comment]
That would be great. I don't have any wide screen monitors myself so can't test it.

**Comment by Ash-Cozey** [comment]
I tried different font scales at 3440x1440, 2560x1440, 2560x1080 and 1920x1080. 

They all worked as long as the vertical resolution was the same, so it looks like horizontal resolution isn't necessary.

**Comment by josdemmers** [comment]
I'll commit the changes this evening.

**Comment by josdemmers** [comment]
Changed the preset names with the v1.1.16 release.

**Pull request closed without merging**
