### PR TITLE
[Partial] 3440x1440 HDR Small fonts

### PR DESCRIPTION
**Pull request by thromera**
Preset for 3440x1440 HDR Small fonts

NB: It's very partial, only a few items. Hopefully it helps others contribute to the preset!

### CODE REVIEW

**Comment by josdemmers** [comment]
Thank you for sharing! Partial data is great as well, makes it a lot easier for others to get started. Noticed you added all images to the project. Adding new presets works a little bit different. Could you change the pull request as follows:
- Create a new 3440x1440_HSF_en.zip containing the 3440x1440_HSF_en folder.
- Update the systempresets.json file.

You can find the other system presets here:
https://github.com/josdemmers/Diablo4Companion/tree/master/downloads/systempresets

Adding it like this will add it to the download manager in the app.

Let me know if you have any questions.

**Comment by thromera** [comment]
✅ all good on my end. 

I assumed the [`TooltipWidth`](https://github.com/josdemmers/Diablo4Companion/pull/22/files#diff-a1d362feef3de9403437f58b89053d08a78e0906e9bde229807b7fe99206df35R21) was the size of the equipment tooltip when taking a screenshot of the whole UX. 
Here is the screenshot I used to measure it.
Screenshot 2023-07-29 163511

💡 To ease contributions, I would like to suggest to not upload .zip files on Github but rather have a script that zip the files when generating the project. That way, no need to uncompress to see the content of the archive and it's a bit easier to not have to zip all the time.

**Comment by josdemmers** [comment]
The tooltip width is the marked area in the debug view. Looks like I forgot to add that to the wiki page.
image

**Comment by josdemmers** [comment]
> To ease contributions, I would like to suggest to not upload .zip files on Github but rather have a script that zip the files when generating the project. That way, no need to uncompress to see the content of the archive and it's a bit easier to not have to zip all the time.

Thanks for the suggestion. It is indeed easier for contributing a few missing affixes but I didn't really like that approach. Used that in the beginning but the project file becomes one big mess when adding/deleting affixes. Will probably become even worse when system presets are added for all 12 languages (multiplied by all different resolutions/configurations).

A single location for all system presets that can be used by the download manager looks a lot cleaner.

**Comment by josdemmers** [comment]
Keeping it separated from the project could work though. Then both images and zip file could be placed in:
`https://github.com/josdemmers/Diablo4Companion/tree/master/downloads/systempresets`

But that is not for now. Will look into that later.

**Pull request merged**
